language: node_js
node_js:
  - '7'

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable

before_install:
  - export CHROME_BIN=chromium-browser

before_script:
- npm install -g @angular/cli
- npm install
- ng build --prod
